### ISSUE TITLE
lib folder missing adafruit_bus_device

### ISSUE THREAD

**Issue by kattni** [nnja/pycon_pybadge_2020#6]
Current code fails on not finding `adafruit_bus_device`.

Code tested successfully once `adafruit_bus_device` was added to `lib` folder.

**Comment by nnja** [comment]
Kattni, I'm not able to reproduce this issue. Maybe it's due to a difference in library versions?

I'm using the libraries from this bundle: `adafruit-circuitpython-bundle-5.x-mpy-20200222`
I'm using CircuitPython version: `adafruit-circuitpython-pybadge-en_US-5.0.0-beta.5.uf2`

Steps I tried on Mac OS:

1. Clear all the files on the PyBadge

`$ rm -rf /Volumes/CIRCUITPY`

2. Navigate to the repo directory

`$ cd pycon_pybadge_2020`

3. Copy all the files from the repo to the badge, excluding the .git directory, .DS_Store files, and .Trashes

`$ rsync -ahP --exclude .Trashes --exclude '.git' --exclude '.DS_Store'  ./ /Volumes/CIRCUITPY`

 Using the steps above, the code runs on a PyBadge LC and I don't see errors about a missing library.

**Comment by kattni** [comment]
I downloaded a zip of master from GitHub and copied everything over. I did it again just now, without including the updated version of PyBadger to be sure it wasn't that. I'm still getting the same failure.

Can you please include a list of the files in your `lib` folder?

**Comment by kattni** [comment]
I figured out the problem. I'm testing it on PyBadge. The failure wouldn't happen on LC. Apologies for the confusion.

**Comment by nnja** [comment]
No problem at all, thanks for the eagle eyes!

Since attendees at PyCon will be getting a Clue, I'll test the code on that device as well. The screen might be too small to properly display the menu, but I'll give it a shot and see what it looks like.
